# display beep in code
print("Please give beep two eyes")
eye = input()
print(f"Beeps expression is now as follows")
print("=========")
print("|\t\t|")
print(f"|\t{eye}\t|")
print("|\t\t|")
print("|\t##\t|")
print("=========")
print("\t||\t")
print("=========")
print("|\t\t|")
print("|\t\t|")
print("|\tBeep|")
print("|\t\t|")
print("|\t\t|")
print("|\t\t|")
print("=========")

